name: Check tests in PR

on:
  pull_request:
    branches: [release]
    types: [opened, reopened, edited]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:

      - name: Get changed files using defaults
        id: changed-files
        uses: trilom/file-changes-action@v1.2.3
        continue-on-error: true

      - name: Run step when a file changes
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: |
          contains(steps.changed-files.outputs.files_modified, 'cypress') == false &&
          contains(steps.changed-files.outputs.files_modified, 'test') == false
        # fail the run if no test files were edited
        run: exit 1
