# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Ok To Test Performance

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-performance-test:
    runs-on: ubuntu-latest
    # Only run for PRs, not issue comments
    if: |
      ${{ github.event.issue.pull_request }}
    steps:
      

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }} # GitHub App installation access token
          reaction-token: ${{ secrets.TOKEN }}
          issue-type: pull-request
          commands: ok-to-perf-test
          named-args: true
          permission: write
